//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineLibrary.Models
{
    using System;
    using System.Collections.Generic;
	using System.ComponentModel.DataAnnotations;

	public partial class Book
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Book()
        {
            this.Feedbacks = new HashSet<Feedback>();
        }
		[Required(ErrorMessage = "Please Book_ID is required")]
		public int BId { get; set; }
		[Required(ErrorMessage = "Please Book_Name is required")]
		[Display(Name = "Book_name")]
		public string Bname { get; set; }
		[Required(ErrorMessage = "Please Book_Author is required")]
		[Display(Name = "Book_Author")]
		public string Bauthor { get; set; }
		[Required(ErrorMessage = "Please Book_Price is required")]
		[DisplayFormat(DataFormatString = "{0:C}", ApplyFormatInEditMode = false)]
		[Display(Name = "Book_Price")]
		public Nullable<int> Bprice { get; set; }
		[Required(ErrorMessage = "Please Number_of_Books is required")]
		public Nullable<int> no_of_books { get; set; }
		[Required(ErrorMessage = "Please Category_ID is required")]
		public int catagry_Id { get; set; }
		[Required(ErrorMessage = "Please Book_URL is required")]
		[DataType(DataType.Url)]
		public string BUrl { get; set; }
    
        public virtual catagry catagry { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Feedback> Feedbacks { get; set; }
    }
}
