//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineLibrary.Models
{
    using System;
    using System.Collections.Generic;
	using System.ComponentModel.DataAnnotations;

	public partial class UsersTable
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UsersTable()
        {
            this.Feedbacks = new HashSet<Feedback>();
        }
		[Required(ErrorMessage = "Please this field is required")]
		public int Id { get; set; }
		[Required(ErrorMessage = "Please this field is required")]
		public string Username { get; set; }
		[Required(ErrorMessage = "Please this field is required")]
		public string Password { get; set; }
		[Required(ErrorMessage = "Please this field is required")]
		public string Email { get; set; }
		[Required(ErrorMessage = "Please this field is required")]
		public string PhoneNo { get; set; }
		[Required(ErrorMessage = "Please this field is required")]
		public int Age { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Feedback> Feedbacks { get; set; }
    }
}
